inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: disable

Layout/BlockAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_block

Layout/CommentIndentation:
  Enabled: true
  AllowForAlignment: true

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_line

Layout/EmptyLineBetweenDefs:
  Enabled: true
  AllowAdjacentOneLineDefs: true

Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: true

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/SpaceAroundOperators:
  Enabled: true
  AllowForAlignment: true

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
